[rpc]
disabled = false
network_address = "http://127.0.0.1:8546"
ws_network_address = "ws://127.0.0.1:8547"

[backends]

# [backends.default_eth]
# type = "ethereum"
# `network_address` is the address of the Ethereum RPC endpoint we are connecting to
# network_address = "ws://127.0.0.1:8545"
# `payout_root_submission_disabled` determines wether the calculated payout roots are submitted to the blockchain via transactions
# payout_root_submission_disabled = true

#   [backends.default_eth.contract_addresses]
#   OntologyStorage = "0x174eab2713537c7e4fb9ea1f4202d909656f2642"
#   RlayToken = "0x28208f2ad2abb7cb82136f1d6234fb0aee8571d2"
#   PropositionLedger = "0x8caf5e029445227ec24cc090026a07b1b521e208"

[backends.myneo4j]
type = "redisgraph"
uri = "redis://127.0.0.1:6379"
graph_name = "rlaygraph"
