data_path = "rlay_data"
network_address = "ws://localhost:8545"
epoch_length = 20
payout_root_submission_disabled = true

[contract_addresses]
OntologyStorage = "0x8caf5e029445227ec24cc090026a07b1b521e208"
RlayToken = "0x28208f2ad2abb7cb82136f1d6234fb0aee8571d2"
PropositionLedger = "0x1cc19ac16ca274152a5e57179bd2051c9ad89876"

[rpc]
disabled = false
network_address = "http://127.0.0.1:8546"
ws_network_address = "ws://127.0.0.1:8547"
