[rpc]
disabled = false
network_address = "http://127.0.0.1:8546"
ws_network_address = "ws://127.0.0.1:8547"

[backends]

[backends.default_eth]
type = "ethereum"
# `network_address` is the address of the Ethereum RPC endpoint we are connecting to
network_address = "ws://127.0.0.1:8545"
# `payout_root_submission_disabled` determines wether the calculated payout roots are submitted to the blockchain via transactions
payout_root_submission_disabled = true

  [backends.default_eth.contract_addresses]
  OntologyStorage = "0xb6ae1328cd90badfd6a8b35210921c95cbff84fe"
  RlayToken = "0x8caf5e029445227ec24cc090026a07b1b521e208"
  PropositionLedger = "0xf008add117ab0f330b5b4f22f710526c47768ab1"

# [backends.myneo4j]
# type = "neo4j"
# uri = "http://neo4j:toasty123@localhost:7474/db/data"
