use std::collections::BTreeMap;

pub fn contract_bins() -> BTreeMap<&'static str, &'static str> {
    let mut bins = BTreeMap::default();
    bins.insert(
        "OntologyStorage",
        include_str!("../data/bins/OntologyStorage.json"),
    );
    bins.insert("RlayToken", include_str!("../data/bins/RlayToken.json"));
    bins.insert(
        "PropositionLedger",
        include_str!("../data/bins/PropositionLedger.json"),
    );

    // LIBRARIES
    bins.insert(
        "ClassStorage",
        include_str!("../data/bins/ClassStorage.json"),
    );
    bins.insert(
        "ObjectIntersectionOfStorage",
        include_str!("../data/bins/ObjectIntersectionOfStorage.json"),
    );
    bins.insert(
        "ObjectUnionOfStorage",
        include_str!("../data/bins/ObjectUnionOfStorage.json"),
    );
    bins.insert(
        "ObjectComplementOfStorage",
        include_str!("../data/bins/ObjectComplementOfStorage.json"),
    );
    bins.insert(
        "ObjectOneOfStorage",
        include_str!("../data/bins/ObjectOneOfStorage.json"),
    );
    bins.insert(
        "ObjectSomeValuesFromStorage",
        include_str!("../data/bins/ObjectSomeValuesFromStorage.json"),
    );
    bins.insert(
        "ObjectAllValuesFromStorage",
        include_str!("../data/bins/ObjectAllValuesFromStorage.json"),
    );
    bins.insert(
        "ObjectHasValueStorage",
        include_str!("../data/bins/ObjectHasValueStorage.json"),
    );
    bins.insert(
        "ObjectHasSelfStorage",
        include_str!("../data/bins/ObjectHasSelfStorage.json"),
    );
    bins.insert(
        "ObjectMinCardinalityStorage",
        include_str!("../data/bins/ObjectMinCardinalityStorage.json"),
    );
    bins.insert(
        "ObjectMaxCardinalityStorage",
        include_str!("../data/bins/ObjectMaxCardinalityStorage.json"),
    );
    bins.insert(
        "ObjectExactCardinalityStorage",
        include_str!("../data/bins/ObjectExactCardinalityStorage.json"),
    );
    bins.insert(
        "DataSomeValuesFromStorage",
        include_str!("../data/bins/DataSomeValuesFromStorage.json"),
    );
    bins.insert(
        "DataAllValuesFromStorage",
        include_str!("../data/bins/DataAllValuesFromStorage.json"),
    );
    bins.insert(
        "DataHasValueStorage",
        include_str!("../data/bins/DataHasValueStorage.json"),
    );
    bins.insert(
        "DataMinCardinalityStorage",
        include_str!("../data/bins/DataMinCardinalityStorage.json"),
    );
    bins.insert(
        "DataMaxCardinalityStorage",
        include_str!("../data/bins/DataMaxCardinalityStorage.json"),
    );
    bins.insert(
        "DataExactCardinalityStorage",
        include_str!("../data/bins/DataExactCardinalityStorage.json"),
    );
    bins.insert(
        "ObjectPropertyStorage",
        include_str!("../data/bins/ObjectPropertyStorage.json"),
    );
    bins.insert(
        "InverseObjectPropertyStorage",
        include_str!("../data/bins/InverseObjectPropertyStorage.json"),
    );
    bins.insert(
        "DataPropertyStorage",
        include_str!("../data/bins/DataPropertyStorage.json"),
    );
    bins.insert(
        "AnnotationStorage",
        include_str!("../data/bins/AnnotationStorage.json"),
    );
    bins.insert(
        "IndividualStorage",
        include_str!("../data/bins/IndividualStorage.json"),
    );
    bins.insert(
        "AnnotationPropertyStorage",
        include_str!("../data/bins/AnnotationPropertyStorage.json"),
    );
    bins.insert(
        "ClassAssertionStorage",
        include_str!("../data/bins/ClassAssertionStorage.json"),
    );
    bins.insert(
        "NegativeClassAssertionStorage",
        include_str!("../data/bins/NegativeClassAssertionStorage.json"),
    );
    bins.insert(
        "ObjectPropertyAssertionStorage",
        include_str!("../data/bins/ObjectPropertyAssertionStorage.json"),
    );
    bins.insert(
        "NegativeObjectPropertyAssertionStorage",
        include_str!("../data/bins/NegativeObjectPropertyAssertionStorage.json"),
    );
    bins.insert(
        "DataPropertyAssertionStorage",
        include_str!("../data/bins/DataPropertyAssertionStorage.json"),
    );
    bins.insert(
        "NegativeDataPropertyAssertionStorage",
        include_str!("../data/bins/NegativeDataPropertyAssertionStorage.json"),
    );
    bins.insert(
        "AnnotationAssertionStorage",
        include_str!("../data/bins/AnnotationAssertionStorage.json"),
    );
    bins.insert(
        "NegativeAnnotationAssertionStorage",
        include_str!("../data/bins/NegativeAnnotationAssertionStorage.json"),
    );

    bins
}
