[package]
name = "rlay-resolve"
version = "0.1.0"
authors = ["Maximilian Goisser <goisser94@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2018"

[dependencies]
rlay_ontology = "0.2.6"
futures = "0.3.0"
